@startuml pattern_config_communication

skinparam BackgroundColor white


skinparam object {
    BorderThickness 1
    FontStyle bold
    BackgroundColor white
    BorderColor black
    FontColor black
    FontSize 16
    AttributeFontSize 16
    BackgroundColor<<FunctionBlock>> CCCCCC
    BackgroundColor<<User-defined Type>> CCCCCC
    BackgroundColor<<Abstract>> FFFFFF
}



skinparam Arrow {
    FontColor black
    Color black
    Thickness 2
    FontSize 16
}


object "ConnectionManager"  as com_manager <<FunctionBlock>>{
    Handles: ConnectionHandle[maxConnectionCount]
    Configurations: ConnectionConfig[maxConnectionCount]
    BlockCalls: ConnectionBlocks[maxConnectionCount]
}

object "ConnectionHandle" as com_handle <<User-defined Type>>{
    Handle: DWORD
    State: INT
    NamespaceTable: INT[]
    Scheduling: ScheduleData
}

object "Reader" as read <<FunctionBlock>>{
    Handles: ConnectionHandle[maxConnectionCount]
    HandleIndex: INT
    Configuration: ReadNodeConfig[]
    Data: UnionType[]
    DataIndex: INT
}

com_manager "1  " *-down-  "1..*  " read : "  Handles"



@enduml