@startuml RegulatoryAssociation

skinparam note {
BackgroundColor 50BED7
BorderColor 005F87
}

skinparam class {
BackgroundColor FFB900
BorderColor EB780A
}


package "Regulatory Association" #BECDD7 {

class AssociatedService
class SubElementaryService

AssociatedService "1" -- "n" SubElementaryService : consists-of >

}

@enduml