@startuml pattern_global_registry

skinparam allow_mixing true
skinparam BackgroundColor white
skinparam ComponentStyle rectangle

skinparam Linetype<<useline>> ortogonal

skinparam note {
    BackgroundColor FCFCFC
    BorderColor 444444
    FontColor 444444
}

skinparam object {
    BorderThickness 1
    RoundCorner 20
    StereotypeFontColor black
    FontStyle bold
    BackgroundColor white
    BorderColor black
    FontColor black

FontSize 16
AttributeFontSize 16

    BorderThickness 1
    RoundCorner 20

    BackgroundColor<<environment>> white
    BackgroundColor<<GlobalDataBlock>> CCCCCC
    BackgroundColor<<Function>> CCCCCC

}

skinparam InterfaceBorderColor Black
skinparam InterfaceBackgroundColor Black

skinparam Arrow {
    FontColor black
    Color black
    Thickness 2
    FontSize 16
}



object "GlobalValueRegistry" as registry <<GlobalDataBlock>>{
    Data: UnionType[]
}
object "SetValue" as set <<Function>>{
    Index: INT
    Data: VARIANT
    Registry: UnionType[]
}
object "GetValue" as get <<Function>>{
    Index: INT
    Registry: UnionType[]
    Data => VARIANT
}


set -right-> registry : use
get -left-> registry : use


@enduml